### ISSUE TITLE
Something went wrong. cron reached maximum iterations.

### ISSUE THREAD

**Issue by radiorz** [47ng/fastify-cron#151]
I let it do cron jobs per minute,so it throw a error that cron reached maximum iterations.
will it happens when i do cron jobs not so often?
```
D:\xxx\node_modules\cron\lib\cron.js:235
                                        throw new Error(
                                        ^

Error: Something went wrong. cron reached maximum iterations.
                                                Please open an  issue (https://github.com/kelektiv/node-cron/issues/new) and provide the following string
                                                Time Zone: "" - Cron String: 0 * * * * * - UTC offset: +08:00 - current Date: Tue Dec 08 2020 17:28:06 GMT+0800
    at CronTime._getNextDateFrom (D:\xxx\node_modules\cron\lib\cron.js:235:12)
    at CronTime.sendAt (D:\xxx\node_modules\cron\lib\cron.js:156:17)
    at CronTime.getTimeout (D:\xxx\node_modules\cron\lib\cron.js:175:29)
    at CronJob.start (D:\xxx\node_modules\cron\lib\cron.js:613:31)
    at Timeout.callbackWrapper [as _onTimeout] (D:\xxx\node_modules\cron\lib\cron.js:665:29)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
[nodemon] app crashed - waiting for file changes before starting...
^Cnpm ERR! path D:\xxx
npm ERR! command failed
npm ERR! signal SIGINT
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c "nodemon app/"

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxx\AppData\Local\npm-cache\_logs\2020-12-05T10_42_03_543Z-debug.log
```
is it bug?are there any ways to handle this problem?

**Comment by franky47** [comment]
This is an issue with `node-cron`, which is used by this package, as indicated in the log you provided.

You can check in their issues if there is a resolution for your problem, or open one there.
